name: Angular Tests

on:
   push:
      branches: [ main ]
   pull_request:

jobs:
   ng-test:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [ 14.x ]
      steps:
         -  uses: actions/checkout@v2
         -  name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
               node-version: ${{ matrix.node-version }}
         -  name: npm ci
            run: npm ci
         -  name: Angular test
            run: npm test -- --watch=false --browsers=ChromeHeadless
